# Generated by Django 5.2.7 on 2025-10-22 13:38

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broyage', '0001_initial'),
        ('packing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packing',
            options={'ordering': ('-date', 'post'), 'verbose_name': 'Packing', 'verbose_name_plural': 'Packing'},
        ),
        migrations.AlterModelOptions(
            name='pannes',
            options={'ordering': ['-date'], 'verbose_name': 'Panne', 'verbose_name_plural': 'Panne'},
        ),
        migrations.AddField(
            model_name='pannes',
            name='broyage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='broyage.broyage'),
        ),
        migrations.AlterField(
            model_name='packing',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 10, 22, 13, 38, 52, 476798, tzinfo=datetime.timezone.utc)),
        ),
    ]
