# Generated by Django 5.2.7 on 2025-11-06 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0002_alter_packing_options_alter_pannes_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packing',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 11, 6, 18, 35, 5, 886843, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='packing',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pannes',
            name='departement',
            field=models.CharField(choices=[('MEC', 'MECANIQUE'), ('ELECT', 'ELECTRIQUE'), ('AUTO', 'AUTOMATISME'), ('LAB', 'LABORATOIRE'), ('PROD', 'PRODUCTION'), ('ARRET PROG', 'ARRET PROGRAMME'), ('CEET', 'CEET'), ('COMM', 'COMMERCIALE')], default='MEC', max_length=50),
        ),
        migrations.AlterField(
            model_name='pannes',
            name='section',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
