# Generated by Django 5.2.7 on 2025-11-06 18:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0003_alter_packing_date_alter_packing_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packing',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 11, 6, 18, 46, 46, 752805, tzinfo=datetime.timezone.utc)),
        ),
    ]
