# Generated by Django 5.2.7 on 2025-11-06 19:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0004_alter_packing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packing',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 11, 6, 19, 43, 32, 18425, tzinfo=datetime.timezone.utc)),
        ),
    ]
