# Generated by Django 5.2.7 on 2025-11-08 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0006_alter_packing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packing',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 11, 8, 18, 41, 44, 32686, tzinfo=datetime.timezone.utc)),
        ),
    ]
