# Generated by Django 5.2.7 on 2025-11-09 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0007_alter_packing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packing',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 11, 9, 13, 32, 53, 285117, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='pannes',
            name='section',
            field=models.CharField(blank=True, choices=[('broyage', 'broyage'), ('packing', 'packing')], max_length=50, null=True),
        ),
    ]
