# Generated by Django 5.2.7 on 2025-11-14 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0008_alter_packing_date_alter_pannes_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='duree_post',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='packing',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 11, 14, 15, 5, 46, 752195, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='post',
            field=models.CharField(choices=[('06H-14H', '06H-14H'), ('14H-22H', '14H-22H'), ('22H-06H', '22H-06H'), ('06H-18H', '06H-18H'), ('18H-06H', '18H-06H')], default='06H-14H', max_length=10),
        ),
    ]
