# Generated by Django 5.2.7 on 2025-10-22 13:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('packing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Totaliseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compt_debut', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('clinker_debut', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('gypse_debut', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('dolomite_debut', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('slug', models.SlugField()),
                ('post', models.ForeignKey(default='06H-14H', on_delete=django.db.models.deletion.CASCADE, to='packing.post')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.site')),
            ],
            options={
                'verbose_name': 'Totaliseur',
                'verbose_name_plural': 'Totaliseur',
                'ordering': ('-date', 'post__post'),
            },
        ),
        migrations.CreateModel(
            name='Broyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('compt_fin', models.DecimalField(decimal_places=2, max_digits=20)),
                ('clinker_fin', models.DecimalField(decimal_places=2, max_digits=20)),
                ('gypse_fin', models.DecimalField(decimal_places=2, max_digits=20)),
                ('dolomite_fin', models.DecimalField(decimal_places=2, max_digits=20)),
                ('dif_compt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dif_clinker', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dif_dolomite', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dif_gypse', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('slug', models.SlugField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packing.post')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('totaliseur', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='broyage.totaliseur')),
            ],
            options={
                'verbose_name': 'Grinding',
                'verbose_name_plural': 'Grinding',
            },
        ),
    ]
