# Generated by Django 5.2.7 on 2025-11-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broyage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='broyage',
            options={'ordering': ['site'], 'verbose_name': 'Grinding', 'verbose_name_plural': 'Grinding'},
        ),
        migrations.AlterField(
            model_name='broyage',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
