# Generated by Django 5.2.7 on 2025-11-14 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broyage', '0002_alter_broyage_options_alter_broyage_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='broyage',
            options={'ordering': ['site', '-date', 'post'], 'verbose_name': 'Grinding', 'verbose_name_plural': 'Grinding'},
        ),
    ]
