# Generated by Django 5.2.7 on 2025-11-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broyage', '0003_alter_broyage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broyage',
            name='dif_clinker',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='broyage',
            name='dif_compt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='broyage',
            name='dif_dolomite',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True),
        ),
    ]
